const COLOR_THEMES = {
  DARK: {
    MAIN_COLOR: '#030304',
    TEXT_COLOR: '#D9D9D9',
    NAVIGATION_COLOR: '#FFFFFF',
    LIGHTER_TEXT_COLOR: '#898989',
    GRADIENT_MAIN_COLOR: '#121212',
    GRADIENT_CENTER_COLOR: '#0A2413',
  },
  LIGHT: {
    MAIN_COLOR: '#f0fcf2',
    TEXT_COLOR: '#091409',
    NAVIGATION_COLOR: '#091409',
    LIGHTER_TEXT_COLOR: '#8db58d',
    GRADIENT_MAIN_COLOR: '#f2fff2',
    GRADIENT_CENTER_COLOR: '#b3fcb4',
  },
}

const STYLES_THEME = {
  FONT_WEIGHT_LIGHT: 300,
  FONT_WEIGHT_SEMI_BOLD: 600,
  FONT_WEIGHT_REGULAR: 400,

  TITLE_LEFT_COLOR: '#00CE2C',
  TITLE_CENTER_COLOR: '#AEDF23',
  TITLE_RIGHT_COLOR: '#A3DC00',

  LOGO_TOP_COLOR: '#2ADD50',
  LOGO_BOTTOM_COLOR: '#AFDD2A',

  TOGGLE_HEIGHT: 27,
  TOGGLE_WIDHT: 50,
  TOGGLE_BORDER_SIZE: 1,

  NAVIGATION_HEIGHT: 103,
  NAVIGATOR_WIDTH: 657,
  NAVIGATOR_MARGIN: 186,
  NAVIGATOR_FONT_SIZE: 20,
  NAVIGATOR_LINE_HEIGTH: 41,

  HEADER_HEIGHT: 417,
  HEADER_MARGIN: 4,
  HEADER_TITLE_WIDTH: 691,
  HEADER_TITLE_MARGIN_LEFT: 100,
  HEADER_TITLE_MARGIN_RIGHT: 100,
  HEADER_TITLE_FONT_SIZE: 76,
  HEADER_TITLE_LINE_HEIGHT: 114,
  HEADER_SUBTITLE_WIDTH: 397,
  HEADER_SUBTITLE_FONT_SIZE: 25,
  HEADER_SUBTITLE_LINE_HEIGHT: 47,

  FOOTER_WIDTH: 1216,
  FOOTER_MARGIN: 10,
  FOOTER_TITLE_FONT_SIZE: 26,
  FOOTER_TITLE_LINE_HEIGHT: 39,
  FOOTER_DECRIPTION_WIDTH: 460,
  FOOTER_DECRIPTION_FONT_SIZE: 24,
  FOOTER_DESCRIPTION_LINE_HEIGHT: 36,
  FOOTER_OPTION_FONT_SIZE: 28,
  FOOTER_OPTION_LINE_HEIGHT: 42,
  FOOTER_TEXT_FONT_SIZE: 24,
  FOOTER_TEXT_LINE_HEIGHT: 29,

  CONTACTS_PADDING: 30,
}

export { COLOR_THEMES, STYLES_THEME }

export type Theme = 'LIGHT' | 'DARK'
